version: '3.8'

volumes:
  mssql_data:

services:
  mssql-server-instance:
    image: mcr.microsoft.com/mssql/server
    ports:
     - "1433:1433"

    restart: always

    #user: root

    volumes:
      - mssql_data:/var/lib/mssqlql/data

    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password10