FROM jetbrains/teamcity-agent:latest as docker_agent

# FROM jetbrains/teamcity-minimal-agent:latest as docker_agent

# USER root

# ENV DOCKER_IN_DOCKER=start

# RUN apt update && \
#     apt install -y apt-utils && \
#     apt-get install -y docker && \
#     apt-get install -y docker-compose 

# USER buildagent